version: '3'

services:
  kripto-backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: kripto/backend:latest
    container_name: kripto-backend
    environment:
      NODE_ENV: production
      API_PREFIX: /api
      MONGODB_URI: mongodb+srv://user:password@cluster0.or29e.mongodb.net/kriptografi_prod?retryWrites=true&w=majority
      PORT: 4000
      GAUTH_CLIENT_ID: example
      GAUTH_CLIENT_SECRET: example
      GAUTH_CALLBACK_URL: example
      SESSION_SECRET: example
      DD_API_KEY: example
    ports:
      - 4000:4000
    restart: unless-stopped
